import Footer from "layouts/Footer/Footer";
import Navbar from "layouts/Navbar/Navbar";
import React from "react";

function TermsAndConditionPage() {
  return (
    <div>
      <Navbar />
      <div className="container-wrapper py-30px">
        <h1 className="white fs-50px mb-40px">Terms & Conditions</h1>
        <div className="mb-70px">
          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            Last Updated: February 20, 2022
          </p>
          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            This website is operated by Empyreals. Throughout the site, the term
            « Empyreals », « we », « us » or « our » as the context may require,
            refer to EMPYREALS. By visiting our site and/or purchasing something
            from us, you engage in our Service and agree to be bound by the
            following terms and conditions.
          </p>
          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            We reserve the right to update, change or replace any part of these
            Terms of services without prior written notice at any time, and it
            is your responsibility to periodically review these Terms of Uses to
            stay informed of updates. Any changes to the Terms will be in effect
            as of the « last updated » referenced on the site.
          </p>
          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            Your continued use of this site after the last updated dates will
            constitute your acceptance of agreement. <br />
            By visiting the website of our products merchants, in particular{" "}
            <a
              href="https://opensea.io/"
              style={{ color: "rgb(53 115 255)" }}
              rel="noreferrer"
              target="_blank"
            >
              www.opensea.io
            </a>
            , you also engage and agree to be bound by their terms and
            conditions.
          </p>

          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            This website is for informational purposes and serves as a binding
            contract for purchasers of EMPYREALS NFTs.
          </p>
          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            Empyreals is a generative collection of digital artwork (NFTs)
            housed and run on the Ethereum Network. Users and Collector of these
            NFTs are solely responsible for the safety and the management of
            their own private assets, which include but are not limited to
            Ethereum Wallets, validating all transactions and contracts
            generated by this website prior to and after purchases.
          </p>
          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            Users certify through purchase that they understand that, as the
            Empyreals smart contract runs on the Ethereum network and is bound
            by their system and terms, there is no ability to undo, reverse, or
            restore any transactions.
          </p>
          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            Any connected services included this website are provided “as is”
            and “as available” without any warranty of any kind. Use of this
            website constitutes your agreement that you are accepting sole
            responsibility for any and all transactions involving Empyreals
            digital collectibles.
          </p>
          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            By agreeing to these Terms of Service, you represent that you are at
            least the age of majority in your state or province of residence.
          </p>
          <br />
          <hr />
          <br />
          <br />
          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            You may not use our products and/or services for any illegal or
            unauthorized purpose nor may you, in the use of the Service, violate
            any laws in your jurisdiction (including but not limited to
            copyright laws).
          </p>
        </div>

        <div className="mb-70px">
          <h2 className="fs-40px white mb-20px">Ownership</h2>

          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            When you purchase your Empyreals NFT, You Own the NFT: the ownership
            is transferred to you on the Ethereum blockchain for that individual
            piece of Art combination of traits and number. Ownership of the NFT
            is ruled by the smart contract and the Ethereum Network terms. We,
            Empyreals, have no ability to alter, freeze, seize or modify the
            ownership of any Empyreals NFT.
          </p>
        </div>

        <div className="mb-70px">
          <h2 className="fs-40px white mb-20px">Personal Usage</h2>
          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            Subject to your continued acceptance with these terms, Empyreals
            allows you a worldwide, royalty-free licence to use, copy and
            display the purchased Art, along with any derivative artwork or
            extensions that you could create or use, limited by the following
            purposes : (i) for your own personal, non-commercial use; (ii) as
            part of a marketplace that allows the purchase and sales of you
            Empyreals / NFT, as long as the marketplace cryptographically
            verifies that you are the owner, to ensure that only the actual
            owner have the right to display the Art; or (iii) as part of a third
            party website or application that permits the inclusion, involvement
            or participation of your Empyreals, provided that the website or the
            application cryptographically verifies each Empyreals owner’s right
            to display the Art for their Empyreals, to ensure that only the
            actual owner can display the Art, and provided that the Art is no
            longer visible once the actual owner of the Empyreals leave the
            website or application.
          </p>
        </div>
        <div className="mb-70px">
          <h2 className="fs-40px white mb-20px">Commercial Usage</h2>
          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            Subject to actual owner of Empyreals NFTs continued compliance with
            these Terms, Empyreals grant you an unlimited, worldwide licence to
            use, copy and display the purchased Art for the purpose of creating
            derivative works based upon the Art (« COMMERCIAL USAGE »). The only
            exception being not to carry out 3D modelling (sale of figurines)
            because we reserve it for the physical part of our drop. Examples of
            specified Commercial Use would be the use of the Art to produce and
            sell physical merchandise products (T-Shirt, Posters, etc.)
            displaying copies of the purchased Art. Please be aware that nothing
            in this section will be deemed to restrict you from (i) owning or
            operating a marketplace that permits the use and sale of Empyreals
            generally, provided that the marketplace cryptographically verifies
            each Empyreals owner’s right to display the Art of their Empyreals
            to ensure that only the actual owner can display the Art; (ii)
            owning or operating a third party website or application that
            permits the inclusion, involvement, or participation of Empyreals
            generally, provided that the third party website or application
            cryptographically verifies each Empyreals owner’s rights to display
            the Art for their Empyreals to ensure that only the actual owner can
            display the Art, and provided that the Art is no longer visible once
            the owner of the Purchased Empyreals leaves the website/application;
            or (iii) earning revenue from any of the foregoing.
          </p>

          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            Further Empyreals reserves the right to use ANY character,
            including: print or digital advertising, or any purely creative
            media (including short film, anime, etc.) in support of the
            Empyreals community and message.
          </p>
          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            However, you cannot use the artwork in connection with images of
            hatred, violence or any other inappropriate behaviour. The License
            granted in above only applies to the extent that you continue to own
            the relevant NFT. If at any time you trade, donate, giveaway,
            transfer or otherwise dispose of your NFT for any reason, the
            license granted above will immediately expire, without notice, and
            you will have no further right in or to the artwork of this NFT.
          </p>
        </div>

        <div className="mb-70px">
          <h2 className="fs-40px white mb-20px">Empyreals IP</h2>

          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            Other than the rights to the Art, nothing gives you any rights to
            any other trademarks or other intellectual property rights belonging
            to Empyreals <br /> including, without limitation Empyreals,
            EMPYREALS and the associated logos. All of these rights are
            expressly reserved in the name of Empyreals.{" "}
          </p>
        </div>

        <div className="mb-150px">
          <h2 className="fs-40px white mb-20px">Feedback</h2>

          <p className="white opacity-0_6 fs-20px weight-4 mb-25px lh-1_5">
            You can submit comments, bug reports, ideas about the site or the
            project. By submitting any feedback, you agree that we are free to
            use them in any way we choose without additional compensation to you
            and you hereby grant us a perpetual, irrevocable, nonexclusive
            worldwide licence to incorporate and use the feedback for any
            purpose.
          </p>
        </div>

        <Footer />
      </div>
    </div>
  );
}

export default TermsAndConditionPage;
